- hosts: web
  become: true
  tasks:
    - name: Update packages
      yum:
        name: "*"
        state: latest

    - name: Install Java 21
      dnf:
        name: java-21-amazon-corretto
        state: present

    - name: Download Minecraft server
      shell: |

        mkdir -p Minecraft
        cd Minecraft
        curl -o minecraft_server.jar https://piston-data.mojang.com/v1/objects/e6ec2f64e6080b9b5d9b471b291c33cc7f509733/server.jar
        echo "eula=true" > eula.txt
    
    - name: Create config file
      copy: 
        dest: /etc/systemd/system/minecraft.service
        content: |
          [Unit] 
          Description=Minecraft Server 
          After=network.target 
          [Service]
          WorkingDirectory=/home/ec2-user/Minecraft
          ExecStart=sudo /usr/bin/java -Xmx2G -Xms1G -jar /home/ec2-user/Minecraft/minecraft_server.jar nogui 
          Restart=on-failure
          [Install] 
          WantedBy=multi-user.target 
      notify: Reload systemd

      
    - name: Start server
      systemd:
        name: minecraft
        enabled: true
        state: started

  handlers:
    - name: Reload systemd
      shell: |
        systemctl daemon-reexec
        systemctl daemon-reload
